services:
  enstow:
    image: ghcr.io/karan/enstow
    container_name: enstow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allows agent to interact with other containers
      - /path/to/backups/dir:/backups
      - /path/to/config.yaml:/app/config.yaml:ro
    environment:
      BACKUP_DIR: "/backups"
      CONFIG_FILE_PATH: "/app/config.yaml"
      CRON_SCHEDULE: "*/1 * * * *"
      TIMEZONE: "UTC"
    restart: on-failure
